using DevExpress.XtraPrinting;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace XtraGridControl
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void gridView1_PrintInitialize(object sender, DevExpress.XtraGrid.Views.Base.PrintInitializeEventArgs e)
        {
            PrintingSystemBase pb = e.PrintingSystem as PrintingSystemBase;
            pb.StartPrint -= pb_StartPrint;
            pb.StartPrint += pb_StartPrint;


        }

        void pb_StartPrint(object sender, PrintDocumentEventArgs e)
        {
            e.PrintDocument.PrinterSettings.Duplex = System.Drawing.Printing.Duplex.Horizontal;
            //e.PrintDocument.PrinterSettings.PrintToFile = true;
            e.PrintDocument.PrinterSettings.PrinterName = "Foxit Reader PDF Printer";

        }

        private void btnPrint_Click(object sender, EventArgs e)
        {
            gridControl1.Print();
        }
    }
}
