Imports DevExpress.XtraGrid.Views.Grid
Imports DevExpress.XtraTreeList.Data

Public Class xtraGoogleSheet
    Sub New()

        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        ' Me.UspGoogleSheetTableAdapter.Fill(_2020BEAMSandBoxDataSetGoogleSheet.uspGoogleSheet, "1/1/2021", "7/1/2021")
    End Sub

    Private Sub GridView1_CustomUnboundColumnData(sender As Object, e As DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs) Handles GridView1.CustomUnboundColumnData
        Dim view As GridView = TryCast(sender, GridView)
        If e.Column.FieldName = "colComplexTimeDetails" AndAlso e.IsGetData Then
            e.Value = getComplexTimeDetails(view, e.ListSourceRowIndex)
        End If
        If e.Column.FieldName = "colNTRCompleted" AndAlso e.IsGetData Then
            e.Value = getNTRCompleted(view, e.ListSourceRowIndex)
        End If

    End Sub
    Private Function getComplexTimeDetails(view As GridView, listSourceRowIndex As Integer) As String
        Dim Customer As String = Convert.ToString(view.GetListSourceRowCellValue(listSourceRowIndex, "CUSTOMER"))
        Dim Complex As String = Convert.ToString(view.GetListSourceRowCellValue(listSourceRowIndex, "Complex"))
        Dim ApptDate As DateTime = Convert.ToDateTime(view.GetListSourceRowCellValue(listSourceRowIndex, "ApptDate"))
        Dim ApptTime As DateTime = Convert.ToDateTime(view.GetListSourceRowCellValue(listSourceRowIndex, "ApptTime"))
        Dim woDescrip As String = Convert.ToString(view.GetListSourceRowCellValue(listSourceRowIndex, "WODescrip"))
        Return Customer + " | " + Complex + " | " + ApptDate + " | " + ApptTime + " | " + woDescrip
    End Function
    Private Function getNTRCompleted(view As GridView, listSourceRowIndex As Integer) As String
        Dim IsCompleted As String = Convert.ToString(view.GetListSourceRowCellValue(listSourceRowIndex, "IsCompleted"))
        Dim DidWhat As String = Convert.ToString(view.GetListSourceRowCellValue(listSourceRowIndex, "DidWhat"))
        Dim Reason As String = Convert.ToString(view.GetListSourceRowCellValue(listSourceRowIndex, "Reason"))
        Dim retString As String = ""
        If IsCompleted Then
            retString = "Completed. " + DidWhat
        Else
            retString = "NTR. " + Reason
        End If

        Return retString
    End Function

    Private Sub xtraGoogleSheet_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        '
        'Initialize the sheet with default values for the current day if a weekday
        ' if not a weekday, drop to previous Friday
        '
        Dim Day As DayOfWeek
        Day = DateTime.Now.DayOfWeek
        If Day <> DayOfWeek.Saturday And Day <> DayOfWeek.Sunday Then
            txtStartDate.Text = DateTime.Today.ToString()
            txtEndDate.Text = DateTime.Today.ToString()
        Else
            '
            'It is a weekend so set the reporting date to Friday
            '
            If Day = DayOfWeek.Saturday Then
                txtStartDate.Text = (DateAdd(DateInterval.Day, -1, DateTime.Today)).ToString
                txtEndDate.Text = (DateAdd(DateInterval.Day, -1, DateTime.Today)).ToString
            ElseIf Day = DayOfWeek.Sunday Then
                txtStartDate.Text = (DateAdd(DateInterval.Day, -2, DateTime.Today)).ToString
                txtEndDate.Text = (DateAdd(DateInterval.Hour, 24, DateTime.Today)).ToString
            End If

        End If
        Me.UspGoogleSheetTableAdapter.Fill(_2020BEAMSandBoxDataSetGoogleSheet.uspGoogleSheet, txtStartDate.Text, txtEndDate.Text)

    End Sub

    Private Sub btnRefresh_Click(sender As Object, e As EventArgs) Handles btnRefresh.Click
        Me.UspGoogleSheetTableAdapter.Fill(_2020BEAMSandBoxDataSetGoogleSheet.uspGoogleSheet, txtStartDate.Text, txtEndDate.Text)

    End Sub
End Class